//
//  Copyright © 2016 Kevin Tatroe. All rights reserved.
//  See LICENSE.txt for this sample’s licensing information

import Foundation


/**
 Applies changes to the `NSMutableURLRequest` generated by an `ServiceRequest` prior
 to turning the URL request into a fetch.
 */
public protocol ServiceRequestDecorator: class {
    func compose(urlRequest: NSMutableURLRequest)
}


/**
 Adds an HTTP header indicating the response can be Gzip compressed.
 */
public class AcceptGZIPHeadersServiceRequestDecorator: ServiceRequestDecorator {
    // MARK: - Initializers

    public init() { }


    // MARK: - Protocols

    // MARK: <ServiceRequestDecorator>

    public func compose(urlRequest: NSMutableURLRequest) {
        urlRequest.setValue("gzip", forHTTPHeaderField: "Accept-Encoding")
    }
}


/**
 Applies its parameters either as GET parameters or by building a POST body payload
 as appropriate for the type of request.
 */
public class HTTPParametersBodyServiceRequestDecorator: ServiceRequestDecorator {
    // MARK: - Properties

    let type: ServiceEndpointType
    let parameters: [String : String]


    // MARK: - Initialization

    public init(type: ServiceEndpointType, parameters: [String : String]) {
        self.type = type
        self.parameters = parameters
    }


    // MARK: - Protocols

    // MARK: <ServiceRequestDecorator>

    public func compose(urlRequest: NSMutableURLRequest) {
        guard !parameters.isEmpty else { return }

        switch type {
        case .get:
            if let requestURL = urlRequest.URL {
                urlRequest.URL = requestURL.urlByAppendingQueryParameters(parameters)
            }

        case .post: fallthrough
        case .put: fallthrough
        case .delete:
            urlRequest.addValue("application/x-www-form-urlencoded", forHTTPHeaderField: "Content-Type")

            var valueStrings = [String]()

            for (key, value) in parameters {
                let encodedValue = value.stringByAddingPercentEncodingWithAllowedCharacters(NSCharacterSet.URLQueryAllowedCharacterSet())
                valueStrings.append("\(key)=\(encodedValue)")
            }

            let requestBody = valueStrings.joinWithSeparator("&")

            let data = requestBody.dataUsingEncoding(NSUTF8StringEncoding)
            urlRequest.HTTPBody = data

        case .header:
            /// TODO: support HEADER requests
            break
        }
    }
}


internal extension NSURL {
    /**
     Provides support for mutating a URL into another by adding query parameters to the
     URL's existing parameters (or by adding query parameters if none already exist).
     */
    func urlByAppendingQueryParameters(parameters: [String : String]?) -> NSURL {
        guard let parameters = parameters else { return self }
        guard let components = NSURLComponents(URL: self, resolvingAgainstBaseURL: false) else { return self }

        for (key, value) in parameters {
            let encodedValue = value.stringByAddingPercentEncodingWithAllowedCharacters(NSCharacterSet.URLQueryAllowedCharacterSet())
            let queryItem = NSURLQueryItem(name: key, value: encodedValue)

            if let _ = components.queryItems {
                components.queryItems?.append(queryItem)
            } else {
                components.queryItems = [queryItem]
            }
        }

        if let url = components.URL {
            return url
        }

        return self
    }
}


/**
 Adds an HTTP header for HTTP Basic authentication.
 */
public class HTTPAuthServiceRequestDecorator: ServiceRequestDecorator {
    private let username: String
    private let password: String
    
    
    public init(username: String, password: String) {
        self.username = username
        self.password = password
    }
    
    
    public func compose(urlRequest: NSMutableURLRequest) {
        let credentials = "\(username):\(password)"
        
        if let data = credentials.dataUsingEncoding(NSUTF8StringEncoding) {
            let credentials = data.base64EncodedStringWithOptions(NSDataBase64EncodingOptions())
            let value = "Basic \(credentials)"
            
            urlRequest.setValue(value, forHTTPHeaderField: "Authorization")
        }
    }
}
